# Generated by Django 4.0 on 2022-02-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0008_rename_name_counrtry_country_name_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_place', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=800)),
                ('category', models.CharField(max_length=30)),
                ('short_info', models.CharField(blank=True, max_length=35, null=True)),
                ('location', models.TextField(blank=True, max_length=400, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
    ]
