# Generated by Django 4.0 on 2022-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id',
            new_name='id_place',
        ),
        migrations.AlterField(
            model_name='place',
            name='order',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], null=True),
        ),
    ]
