# Generated by Django 4.0 on 2022-02-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_rename_id_place_id_place_alter_place_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id_place',
            new_name='id',
        ),
    ]
