# Generated by Django 4.0 on 2022-02-19 14:50

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_place_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageplace',
            name='describe',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='imageplace',
            name='image',
            field=models.ImageField(upload_to=place.models.upload_image),
        ),
    ]
