# Generated by Django 4.0 on 2022-02-19 15:10

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_imageplace_describe_alter_imageplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='background',
            field=models.ImageField(null=True, upload_to=place.models.upload_image_background),
        ),
    ]
