# Generated by Django 4.0 on 2022-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_place_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='describe',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('classA', (('', 'مناطق تاريخية'), ('', 'آثار'), ('', 'متاحف ومعارض فنية'))), ('classB', (('', ' شواطئ'), ('', 'شالات'), ('', 'منتجعات'))), ('classC', (('', ' حدائق'), ('', 'حدائق حيوانات'), ('', ' محميات طبيعة'), ('', ' جزر'))), ('classD', (('', 'مسارح'), ('', 'مدن ملاه '), ('', 'مراكز تسوق  '))), ('classE', (('', 'مساجد'), ('', 'كنائس'), ('', 'أماكن مقدسه اسلاميه'), ('', 'أماكن مقدسه مسيحية')))], max_length=50),
        ),
    ]
