# Generated by Django 4.0 on 2022-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_alter_imageplace_describe_alter_place_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_activity', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('classA', (('A', 'مناطق تاريخية'), ('B', 'آثار'), ('C', 'متاحف ومعارض فنية'))), ('classB', (('D', ' شواطئ'), ('E', 'شالات'), ('F', 'منتجعات'))), ('classC', (('park', ' حدائق'), ('animal park', 'حدائق حيوانات'), ('S', ' محميات طبيعة'), ('Z', ' جزر'))), ('classD', (('V', 'مسارح'), ('V1', 'مدن ملاه '), ('v2', 'مراكز تسوق  '))), ('classE', (('v3', 'مساجد'), ('v4', 'كنائس'), ('v5', 'أماكن مقدسه اسلاميه'), ('v6', 'أماكن مقدسه مسيحية')))], max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='activity',
            field=models.ManyToManyField(to='place.Activity'),
        ),
    ]
