# Generated by Django 4.0 on 2022-02-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_activity_alter_place_category_place_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='activity',
        ),
    ]
