# Generated by Django 4.0 on 2022-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_activity_category_activity_image_activity_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
