# Generated by Django 4.0 on 2022-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_alter_place_short_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
