# Generated by Django 4.0 on 2022-02-24 03:39

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='background',
            field=models.ImageField(upload_to=place.models.upload_image_background),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('classA', (('A', 'مناطق تاريخية'), ('B', 'آثار'), ('C', 'متاحف ومعارض فنية'))), ('classB', (('D', ' شواطئ'), ('E', 'شالات'), ('Ee', 'بحيرات'), ('F', 'منتجعات'))), ('classC', (('park', ' حدائق'), ('air', ' أنشطة الهواء الطلق'), ('animal park', 'حدائق حيوانات'), ('S', ' محميات طبيعة'), ('Z', ' جزر'))), ('classD', (('V', 'مسارح'), ('V1', 'مدن ملاه '), ('v2', 'مراكز تسوق  '))), ('classE', (('v3', 'مساجد'), ('v4', 'كنائس'), ('v5', 'أماكن مقدسه اسلاميه'), ('v6', 'أماكن مقدسه مسيحية')))], max_length=50),
        ),
    ]
