# Generated by Django 4.0 on 2022-02-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0018_review_profile_alter_place_short_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
