# Generated by Django 4.0 on 2022-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_remove_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
