# Generated by Django 4.0 on 2022-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0021_place_created_at_place_user_alter_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='alert',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
