# Generated by Django 4.0 on 2022-03-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0023_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='comment',
        ),
    ]
