# Generated by Django 4.0 on 2022-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0027_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sea_activity', 'أنشطة البحار'), ('adventures', ' مغامرات'), ('sport', ' رياضه'), ('control', 'قياده وتحكم'), ('family_activity', ' نشاط عائلي'), ('marketing', '  تسوق')], max_length=80),
        ),
    ]
