# Generated by Django 4.0 on 2022-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0029_alter_place_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sea_activity', 'أنشطة البحار'), ('adventures', ' مغامرات'), ('sport', ' رياضه'), ('control', 'قياده وتحكم'), ('family_activity', ' نشاط عائلي'), ('marketing', ' تسوق')], max_length=80),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('التاريخ والأثار', (('historical', 'مناطق تاريخية'), ('archaeological', 'معالم اثريه'), ('museums', 'متاحف ومعارض فنية'))), ('معالم بحيريه', (('Beach', ' شواطئ'), ('lakes', 'بحيرات وشلالات'), ('resorts', 'منتجعات'))), ('معالم طبيعيه', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('islands', ' جزر'))), ('معالم حديثه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('Markets', 'مراكز تسوق  '))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.TextField(default='None', max_length=800),
        ),
        migrations.AlterField(
            model_name='place',
            name='short_info',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
