# Generated by Django 4.0 on 2022-04-23 09:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0030_alter_activity_category_alter_place_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='relevance',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('التاريخ والأثار', (('historical', 'مناطق تاريخية'), ('archaeological', 'معالم اثريه'), ('museums', 'متاحف ومعارض فنية'))), ('معالم بحيريه', (('Beach', ' شواطئ'), ('lakes', 'بحيرات وشلالات'), ('resorts', 'منتجعات'))), ('معالم طبيعيه', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('islands', ' جزر'))), ('معالم حديثه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('Markets', 'مراكز تسوق  '))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='alert',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
