# Generated by Django 4.0 on 2022-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0032_remove_place_relevance_place_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('التاريخ والأثار', (('historical', 'مناطق تاريخية'), ('archaeological', 'معالم اثريه'), ('museums', 'متاحف ومعارض فنية'))), ('معالم بحيريه', (('Beach', ' شواطئ'), ('lakes', 'بحيرات وشلالات'), ('resorts', 'منتجعات'))), ('معالم طبيعيه', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('islands', ' جزر'), ('mountains', ' جبال'))), ('معالم حديثه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('Markets', 'مراكز تسوق  '), ('stadium', 'ملاعب'), ('gyms', 'صالات رياضيه'))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], max_length=50),
        ),
    ]
