# Generated by Django 4.0 on 2022-07-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0033_alter_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='actvity',
        ),
    ]
