# Generated by Django 4.0 on 2022-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0039_remove_activity_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
    ]
