# Generated by Django 4.0 on 2022-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0040_remove_place_created_at_remove_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sea_activity', 'أنشطة البحار'), ('adventures', ' مغامرات'), ('sport', ' رياضه'), ('control', 'قياده وتحكم'), ('family_activity', ' نشاط عائلي'), ('marketing', ' تسوق')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('التاريخ والأثار', (('historical', 'مناطق تاريخية'), ('archaeological', 'معالم اثريه'), ('museums', 'متاحف ومعارض فنية'))), (' شؤاطى ومنتجعات', (('Beach', ' شواطئ'), ('lakes', 'بحيرات وشلالات'), ('resorts', 'منتجعات'))), ('معالم طبيعيه', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('islands', ' جزر'), ('mountains', ' جبال'))), ('معالم حديثه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('Markets', 'مراكز تسوق  '), ('stadium', 'ملاعب'), ('gyms', 'صالات رياضيه'))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], max_length=50),
        ),
    ]
