# Generated by Django 4.0 on 2022-07-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0041_alter_activity_category_alter_place_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
