# Generated by Django 4.0 on 2022-07-17 15:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0044_place_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('', (('historical', 'مناطق تاريخية'), ('archaeological', 'معالم اثريه'), ('museums', 'متاحف ومعارض فنية'))), ('beach', (('beach', ' شواطئ'), ('lake', 'بحيرات وشلالات'), ('resort', 'منتجعات'), ('island', 'جزر'))), ('الطبيعة والمتزهات', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('mountains', ' جبال'))), ('المغامرات والترفيه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('Markets', 'مراكز تسوق  '), ('stadium', 'ملاعب'), ('gyms', 'صالات رياضيه'))), (' التسوق والاستجمام', (('shopping_centers', ' مراكز تسوق'), ('traditional_markets', ' أسواق شعبية'), ('recreation_centers', ' مراكز الاستجمام '))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('families', 'مناسب للعائلات'), ('Children', 'مناسب للأطفال'), ('couples', 'مناسب للأطفال'), ('groups', 'مناسب للمجموعات'), ('Internet', 'إنترنت مجاني'), ('delivery', 'توصيل '), ('parking', ' موقف سيارات متاح'), ('Indoor_yards', 'ساحات داخليه '), ('outdoor_yards', 'ساحات خارجيه'), ('green_yards', 'ساحات خضراء')], max_length=97),
        ),
    ]
