# Generated by Django 4.0 on 2022-07-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0047_alter_place_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
