# Generated by Django 4.0 on 2022-07-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0051_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default='cup', max_length=300),
            preserve_default=False,
        ),
    ]
