# Generated by Django 4.0 on 2022-07-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0052_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='title_place',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
