# Generated by Django 4.0 on 2022-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0053_alter_place_slug_alter_place_title_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title_place',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
