# Generated by Django 4.0 on 2022-07-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0054_alter_place_title_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='title_place',
            new_name='title',
        ),
    ]
