# Generated by Django 4.0 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0056_remove_place_title_place_title_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='info',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
