# Generated by Django 4.0 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0057_alter_activity_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='info',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
