# Generated by Django 4.0 on 2022-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0058_alter_activity_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('فن وثقافة', (('historical', 'تاريخ وآثار'), ('Architectural', 'هندسة المعمارية'), ('museums_galleries', 'متاحف ومعارض فنية'), ('arts_crafts', 'فنون وحرف يدويه'))), ('beach', (('beach', ' شواطئ'), ('lake', 'بحيرات وشلالات'), ('resort', 'منتجعات'), ('island', 'جزر'), ('Harbor', 'مؤانى'))), ('الطبيعة والمتزهات', (('park', ' حدائق'), ('air', ' أنشطة الهواءالطلق'), ('Sanctuaries_zoos', ' محميات و حدائق حيوانات '), ('forests', ' غابات'))), ('المغامرات والترفيه', (('theaters', 'مسارح'), ('amusement', 'ملاهي '), ('stadium', 'ملاعب'), ('gyms', 'صالات رياضيه'))), (' التسوق والاستجمام', (('shopping_centers', ' مراكز تسوق'), ('traditional_markets', ' أسواق شعبية'), ('recreation_centers', 'منتجع صحي '))), ('معالم دينيه', (('mosques', ' مساجد'), ('house_worship', 'دور عباده'), ('Holy_places', 'أماكن مقدسه ')))], max_length=50),
        ),
    ]
