# Generated by Django 4.0 on 2022-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_counrtry', models.CharField(max_length=30)),
                ('formal_country', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(max_length=500)),
                ('capital', models.CharField(max_length=50)),
                ('formal_lang', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('area_country', models.DecimalField(decimal_places=2, max_digits=12)),
                ('continent', models.CharField(choices=[('asia', 'اسيا'), ('africa', 'أفريقيا'), ('europe', 'أوروبا'), ('north_america', 'أمريكا الشمالية'), ('south_america', 'أمريكا الجنوبية'), ('australia', 'أستراليا')], max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
