# Generated by Django 4.0 on 2022-02-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='order_city',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
    ]
