# Generated by Django 4.0 on 2022-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_city_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='area_country',
        ),
    ]
