# Generated by Django 4.0 on 2022-02-15 11:50

import country.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_alter_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCity',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to=country.models.ImageUpload)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city')),
            ],
        ),
    ]
