# Generated by Django 4.0 on 2022-02-15 13:05

import country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_imagecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=country.models.ImageUploadCity),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=country.models.ImageUploadCountry),
        ),
    ]
