# Generated by Django 4.0 on 2022-02-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_city_image_country_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_counrtry',
            new_name='name_country',
        ),
    ]
