# Generated by Django 4.0 on 2022-02-18 07:57

import country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_rename_name_counrtry_country_name_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to=country.models.ImageUploadCity),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
