# Generated by Django 4.0 on 2022-04-16 04:53

import country.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0011_reviewcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ambulance',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='cost_living',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='firefighting',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='police',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_regio', models.CharField(max_length=30)),
                ('info', models.TextField(max_length=500)),
                ('formal_lang', models.CharField(max_length=50)),
                ('cost_living', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('image', models.ImageField(upload_to=country.models.ImageUploadRegion)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
        ),
    ]
