# Generated by Django 4.0 on 2022-04-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_country_ambulance_country_cost_living_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name_country']},
        ),
    ]
