# Generated by Django 4.0 on 2022-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
