# Generated by Django 4.0 on 2022-04-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0014_country_order_region_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['order_city']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.region'),
        ),
    ]
