# Generated by Django 4.0 on 2022-04-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0015_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='info',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='country',
            name='info',
            field=models.TextField(max_length=1000),
        ),
    ]
