# Generated by Django 4.0 on 2022-07-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0017_popularquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularquestion',
            name='answer',
            field=models.TextField(max_length=500),
        ),
    ]
