# Generated by Django 4.0 on 2022-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0022_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
