# Generated by Django 4.0 on 2022-07-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0023_country_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
