# Generated by Django 4.0 on 2022-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_partspost_alt_image_post_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('advices', 'نصائح'), ('suggestions', 'اقتراحات'), ('public', 'عامه')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
