# Generated by Django 4.0 on 2022-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partspost',
            name='alt_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ImagesPartsPost/'),
        ),
    ]
