# Generated by Django 4.0 on 2022-07-31 17:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partspost',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('advices', 'نصائح'), ('suggestions', 'اقتراحات'), ('public', 'عامه'), ('learning', 'محتوى تعليمي')], max_length=100),
        ),
    ]
