# Generated by Django 4.0 on 2022-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('PS', 'فلسطين'), ('JAD', 'الأردن'), ('EGY', 'مصر'), ('AUS', 'السعودية'), ('EUS', 'الامارات '), ('AJZ', 'الجزائر')], max_length=40)),
                ('brithdate', models.DateField()),
                ('person_image', models.ImageField(upload_to='UserImages/')),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'انثى')], max_length=10)),
            ],
        ),
    ]
