# Generated by Django 4.0 on 2022-02-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brithdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
