# Generated by Django 4.0 on 2022-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='person_image',
            field=models.ImageField(default='', upload_to='UserImages/'),
            preserve_default=False,
        ),
    ]
