# Generated by Django 4.0 on 2022-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0024_remove_favorite_comment'),
        ('accounts', '0008_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.plans')),
            ],
        ),
    ]
