# Generated by Django 4.0 on 2022-03-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_plans_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='tour_type',
            field=models.CharField(choices=[('worship', 'عبادة '), ('romantic-tourism', 'قضاء شهر العسل'), ('family', 'عائلتي'), ('friends', 'أصدقائي'), ('Safari', 'سفاري'), ('medical', 'علاجية')], max_length=30),
        ),
    ]
