# Generated by Django 4.0 on 2022-07-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_plans_tour_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], max_length=10),
        ),
    ]
