# Generated by Django 4.0 on 2022-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('PS', 'فلسطين'), ('JAD', 'الأردن'), ('EGY', 'مصر'), ('AUS', 'السعودية'), ('EUS', 'الامارات '), ('AJZ', 'الجزائر')], max_length=40),
        ),
    ]
